### ISSUE TITLE
False positive in tokio

### ISSUE THREAD

**Issue by mathstuf** [est31/cargo-udeps#31]
On tokio-rs/tokio#1656 with the `-Z minimum-versions` and commenting out the `build-tests` crate, I get this false positive report:

```
unused dependencies:
`tokio-net v0.2.0-alpha.6 (/home/boeckb/code/depot/lang-rust/proj-tokio/tokio/src/tokio-net)`
└─── (dev-)dependencies
     └─── "tokio-net"
```

Or at least it appears to be a false positive since there's no `tokio-net` dependency in…itself (not even an older version).

Attaching the `save-analysis` directory generated from the run.

[cargo-udeps-tokio-false-positive.tar.gz](https://github.com/est31/cargo-udeps/files/3722673/cargo-udeps-tokio-false-positive.tar.gz)

**Comment by qryxip** [comment]
[When a `lib` target is found, `cargo-udeps` regards it as a dependency](https://github.com/est31/cargo-udeps/blob/56c152bfc7923dde3e11564f42c20a5a6351f8ef/src/lib.rs#L325-L332) because `bin`s, `test`s, and `example`s should depends on it. The `save-analysis` does not seem to contain `test`s. (`test-cat` is a `bin` target)

Currently, you need to run with `--all-targets` to find dependencies that are not used by any target.

![screenshot_000](https://user-images.githubusercontent.com/14125495/66732643-b2dfe200-ee97-11e9-878d-e759b99b5ebd.png)

**Comment by qryxip** [comment]
> [When a `lib` target is found, `cargo-udeps` regards it as a dependency](https://github.com/est31/cargo-udeps/blob/56c152bfc7923dde3e11564f42c20a5a6351f8ef/src/lib.rs#L325-L332) because `bin`s, `test`s, and `example`s should depend on it. The `save-analysis` does not seem to contain `test`s. (`test-cat` is a `bin` target)

After thinking about it, this it not necessary. We want to find unused dependencies, not connected components of graphs.
