### ISSUE TITLE
cargo-udeps.toml

### ISSUE THREAD

**Issue by qryxip** [est31/cargo-udeps#45]
Like this.

```toml
[ignore.foo]
normal_dev = []
build = ["cargo-lipo"]
```

**Comment by est31** [comment]
Good idea! Instead of a separate file, I'd prefer to put it into the [metadata table in Cargo.toml](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table-optional).

**Comment by est31** [comment]
Commit 9123f978701c3244fdcd5b0bb7d670099d1dde2e has fixed a bug by enabling some syn features. However, in order to do that, syn needs to be added to Cargo.toml even though we don't use it directly, and this leads to a warning when we run cargo-udeps on itself.

With this feature, we could suppress the warning.
