### ISSUE TITLE
Running multiple times

### ISSUE THREAD

**Issue by oconnor663** [est31/cargo-udeps#5]
If I have a project with an unused dependency, the first run reports:

    unused crates: [...]

But running `cargo +nightly udeps` again reports:

    All deps seem to have been used.

Is there a way to cache the results or something, so they can be reported again from subsequent runs?

**Comment by est31** [comment]
Thanks for the report! Yes, the caching behaviour is not perfect atm. Actually, the info is still stored on disk it just doesn't have the list of relevant file names. [I've tried to improve it](https://github.com/est31/cargo-udeps/tree/dry_run) by doing a "dry run" before the actual build but sadly it doesn't really work because it re-runs build.rs which invalidates caches further down, yielding in a partial full rebuild of the entire crate graph. This is basically a limitation/bug of the `Executor` trait as it isn't called for build.rs script execution. @ehuss is this behaviour intended or should I file a bug?

I don't think that cargo-udeps should rebuild the entire chain each time it runs. Maybe one can only invalidate "local" crates, but the invalidation check function doesn't give you information that would directly tell you whether the crate is local or not. Or one can use the new build plan feature of cargo and determine the save analysis file names from that (build plans would be proper "dry run"'s).

**Comment by andjo403** [comment]
is this the same fault that I hade when first running `cargo +nightly udeps` and then `cargo +nightly udeps --lib`? was a bit confused when I got the result `All deps seem to have been used.` for both times when testing on pulldown-cmark that I know from before hade unused dependency in lib but not in bin

**Comment by est31** [comment]
@andjo403 yes it should be the same problem. A possible cleanup command is `rm target/debug/deps/libpulldown*.rmeta`.

**Comment by qryxip** [comment]
There are more (well-known) methods to force rebuilding.

- [`cargo:rerun-if-changed` in `build.rs`](https://stackoverflow.com/questions/49077147/how-can-i-force-build-rs-to-run-again-without-cleaning-my-whole-project)

- `cargo clean --package <SPEC>...`

```
cargo clean -p $PACKAGE_NAMES && cargo +nightly udeps
```

- `touch`ing source files

```
$ cargo metadata --format-version 1 |
  jq -r '.workspace_members[] as $members | .packages[] | select(.id == $members) | .targets[].src_path' |
  xargs touch &&
cargo +nightly udeps
```

or

```bash
#!/bin/bash

cargo metadata --format-version 1 |
  jq -r '.workspace_members[] as $members | .packages[] | select(.id == $members) | .targets[].src_path' |
  xargs touch
```

```
$ exa -l ~/.cargo/bin/cargo-touch-workspace
.rwxr-xr-x 170 me  1 Jan 00:00 /home/me/.cargo/bin/cargo-touch-workspace
$ cargo touch-workspace && cargo +nightly udeps
```
