### ISSUE TITLE
Why must this crate compile with nightly?

### ISSUE THREAD

**Issue by Nicholas-Baron** [est31/cargo-udeps#73]
I find it strange that a crate can be installed with stable, but must use nightly to run.

Trying to compile with stable gives the following error
> the option `Z` is only accepted on the nightly compiler

Has the source of this error been tracked down? I do not see anything in this repository explicitly so it must be in one of the dependencies.

**Comment by qryxip** [comment]
That message comes from `rustc`.

```console
$ rustc +stable -Z aaaaaaaaaa /dev/null
error: the option `Z` is only accepted on the nightly compiler
```

The reason is because `cargo-udeps` relies on the `-Z save-analysis` option, which is only available on `nightly`. So `cargo-udeps` itself does not need to be compiled with `nightly` toolchains.

https://github.com/est31/cargo-udeps/blob/82b1ede9fbff3102f0ee2d778f34c810ddcb532b/src/lib.rs#L608

**Comment by est31** [comment]
Yeah you can switch between `save-analysis` and `binary-depinfo` backends but both currently require nightly. save-analysis will likely be removed eventually but binary-depinfo might get stabilized. Maybe a backend based on the unused dependency warning can be added, that one would work on stable, cc #70.
