### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by piotrmaks** [est31/cargo-udeps#75]
Have you considered enabling https://github.com/marketplace/dependabot-preview?

**Comment by est31** [comment]
I don't think dependabot is very helpful. Fist, it creates tons of spam by suggesting to increase the patch version numbers in Cargo.toml. Second, that spam makes it harder to git bisect because you have to rebuild larger parts of your dependency tree.

I rather run cargo update and cargo outdated regularly, i.e. once per month. For cargo-udeps, as it depends on cargo, it's once per Rust release.
