### ISSUE TITLE
Add option to fail silently

### ISSUE THREAD

**Issue by morenol** [est31/cargo-udeps#95]
It would be great to add an option to make udeps finish with exit code 0  if there is an unused dependency.

Let me know if you think that you would accept this feature and I could try to give it a shoot.

**Comment by est31** [comment]
Hi @morenol! What exactly do you want to do? If cargo udeps finds an unused dependency, it does send a non zero exit code so that it can be used in shell scripting use cases. Also, it's quite easy to make udeps entirely silent by redirecting output streams to /dev/null. Do you want a mode that outputs other warnings but not the unused dependencies? Or do you want the "all dependencies seem to have been used" message gone?

**Comment by morenol** [comment]
Basically what I wanted to run that in a Github Action workflow and make it create annotations in the code instead of failing. But probably I can do that without this feature. Thanks!
